---

- group:
    name: tilde
    state: present

- group:
    name: sudo
    state: present
    
# Service accounts
- include: users/bzflag.yml
- include: users/minecraft.yml
- include: users/znc.yml

# Normal Users

- include: users/deepend.yml
- include: users/naglfar.yml
- include: users/computertech.yml
- include: users/haivets.yml
- include: users/redhat.yml
- include: users/voynich.yml
- include: users/xhafa.yml
- include: users/samsara.yml
- include: users/mcornick.yml
- include: users/fria.yml
- include: users/mspe.yml
- include: users/nbsp.yml
- include: users/user.yml
- include: users/slip.yml
- include: users/login.yml
- include: users/riftwalkr.yml
- include: users/gooly.yml
- include: users/slackjeff.yml
- include: users/haras.yml
- include: users/d34d.yml
- include: users/olivier.yml
- include: users/jimmy.yml
- include: users/vt.yml
- include: users/mahkno.yml
- include: users/radhesh1.yml
- include: users/laniku.yml
- include: users/sebz.yml
- include: users/lowusage.yml
